language: ruby

rvm:
  - 2.1.9
  - 2.2.6
  - 2.3.3
  - 2.4.0

sudo: required
dist: trusty

before_install:
  - gem install minitest -v '5.9.0'
  - gem install webmock -v '2.1.0'
  - gem install http -v '2.0.1'
script: rake test

notifications:
  email:
    on_success: never
